application: simpleeditionsapp
version: 1
runtime: python
api_version: 1

default_expiration: "365d"

handlers:
- url: /static
  static_dir: static

- url: /favicon.ico
  static_files: static/images/favicon.ico
  upload: static/images/favicon\.ico

- url: /stats.*
  script: $PYTHON_LIB/google/appengine/ext/appstats/ui.py

- url: /.*
  script: app.py
